server:
  port: 9191
  servlet:
    context-path: /notification

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz  # Cấu hình kết nối MySQL
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: true  # Tự động tạo topic nếu cần thiết
  mail:
    host: smtp.gmail.com
    port: 587
    username: dangngocduong2509@gmail.com
    password: qenz zvxi qzdy lupo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: "--"



jwt:
  signerKey: ""
  valid-duration: 3600  # in seconds
  refreshable-duration: 720000  # in seconds
